pool:
  name: 'MyAgentPool'
  vmImage: 'windows-latest'

jobs:
- job: Build
  pool:
    name: 'MyAgentPool'
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.0.4'
      installationPath: $(Agent.ToolsDirectory)/dotnet
  - script: dotnet build
    displayName: 'Build Project'

